title: Heroes
nav:
  - index.md
  - introduction.md
  - the-basics.md
  - making-a-hero.md
  - ancestries.md
  - background.md
  - classes.md
  - kits.md
  - perks.md
  - complications.md
  - tests.md
  - combat.md
  - negotiation.md
  - downtime-projects.md
  - rewards.md
  - gods-and-religion.md
  - for-the-director.md
