title: Retainer
nav:
  - index.md
  - angulotl-hopper.md
  - angulotl-hopper-advancement-features.md
  - bugbear-commando.md
  - bugbear-commando-advancement-features.md
  - devil-defector.md
  - devil-defector-advancement-features.md
  - dwarf-mortar.md
  - dwarf-mortar-advancement-features.md
  - gnoll-gnasher.md
  - gnoll-gnasher-advancement-features.md
  - goblin-guide.md
  - goblin-guide-advancement-features.md
  - high-elf-weatherwise.md
  - high-elf-weatherwise-advancement-features.md
  - hobgoblin-flameslinger.md
  - hobgoblin-flameslinger-advancement-features.md
  - human-warrior.md
  - human-warrior-advancement-features.md
  - kobold-shieldbearer.md
  - kobold-shieldbearer-advancement-features.md
  - minotaur-gorer.md
  - minotaur-gorer-advancement-features.md
  - orc-charger.md
  - orc-charger-advancement-features.md
  - radenwight-sidekick.md
  - radenwight-sidekick-advancement-features.md
  - shadow-elf-shade.md
  - shadow-elf-shade-advancement-features.md
  - the-nameless.md
  - the-nameless-advancement-features.md
  - time-raider-mind-healer.md
  - time-raider-mind-healer-advancement-features.md
  - troll-mercenary.md
  - troll-mercenary-advancement-features.md
  - undead-servitor.md
  - undead-servitor-advancement-features.md
  - unquiet-spirit.md
  - unquiet-spirit-advancement-features.md
  - vampire-rebel.md
  - vampire-rebel-advancement-features.md
  - wode-elf-arrowswift.md
  - wode-elf-arrowswift-advancement-features.md
  - role-advancement
